version: 0.2

  #env:
  #variables:
  # key: "value"
  # key: "value"
  #parameter-store:
  # key: "value"
# key: "value"

phases:
  #install:
  #commands:
  # - command
  # - command
  #pre_build:
  #commands:
  # - command
  # - command
  build:
    commands:
    - mvn clean install
    # - command
    #post_build:
    #commands:
    # - command
    # - command
artifacts:
  files:
  - target/todo-demo-app-1.2.0-executable.jar
  # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
cache:
  paths:
  - '/root/.m2/**/*'