apiVersion: v1
kind: Template
labels:
  template: todo-app-build-config
metadata:
  name: todo-app-build-config
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: todo-app
      app: todo-app
    name: todo-app
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: todo-app:latest
    runPolicy: Serial
    source:
      git:
        uri: ${TODO_APP_REPOSITORY}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: spring-offline-s2i:latest
      type: Source
    successfulBuildsHistoryLimit: 5

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: todo-app
    labels:
      app: todo-app
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

parameters:
- name: TODO_APP_REPOSITORY
  displayName: Repository url
  description: The URL of the source repository
  required: true
  value: http://gogs.192.168.99.101.nip.io/sven/todo-app.git