stage('dev') {
    node{
        checkout scm

        openshift.withProject( "todo-app-dev" ) {
            def buildTemplate = openshift.process("-f infra/yml/s2i-todo-app-build-template.yml")
            openshift.apply(buildTemplate)

            openshift.startBuild("todo-app", "--wait=true")
        }
    }
}

